# Generated by Django 4.0 on 2022-04-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_portal', '0004_alter_category_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoryType',
            field=models.CharField(choices=[('NW', 'Новость'), ('AR', 'Статья')], max_length=2, verbose_name='Категория публикации'),
        ),
    ]
