# Generated by Django 4.0 on 2022-04-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_portal', '0005_alter_post_categorytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postText_en',
            field=models.TextField(null=True, verbose_name='текст публикации'),
        ),
        migrations.AddField(
            model_name='post',
            name='postText_ru',
            field=models.TextField(null=True, verbose_name='текст публикации'),
        ),
        migrations.AddField(
            model_name='post',
            name='postTitle_en',
            field=models.CharField(max_length=255, null=True, verbose_name='название публикации'),
        ),
        migrations.AddField(
            model_name='post',
            name='postTitle_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='название публикации'),
        ),
    ]
