# Generated by Django 4.0 on 2022-04-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_portal', '0006_post_posttext_en_post_posttext_ru_post_posttitle_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='categoryname_en',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='category',
            name='categoryname_ru',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='Категория'),
        ),
    ]
